### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#76] opened 2016-04-18 18:54 UTC
Potential sponsor. Box ticked == has been contacted --> put your name after the company name in parens.
~~strike through~~ == out
**bold** == accepted
- [x] Pineapple Media (Ben)
- [x] **Wunderlist/Microsoft** (Franka) [venue + drinks]
- [x] Fy (Jelle)
- [x] **Babbel** (Nicola) [notebooks]
- [x] **SoundCloud** (Arne)
- [x] Futurice (julia)
- [ ] Ticketsolve
- [ ] ~~Dawanda~~
- [ ] Hitfox
- [ ] InnoQ
- [ ] Asquera
- [ ] Github 
- [ ] Thoughtworks
- [x] **Cognitect (Arne)** Gold sponsor = notebooks, ~€500 
- [ ] Juxt 
- [ ] Blacklane
- [ ] O'Reilly
- [ ] PurelyFunctional.tv
- [ ] Pragmatic Programmers
- [ ] Jayway
- [ ] ImmoScout
- [ ] Zalando
- [ ] Otto
- [ ] codecentric
- [ ] Mixcloud
- [ ] Twilio
- [ ] Tape.tv
- [x] Contenful(Malwine)
- [ ] Siili
- [ ] Adjust 
- [x] **Metosin** (franka)
- [x] **Lambdawerk (franka)** = 250
- [ ] MixRadio
- [ ] ableton
- [x] ~~bitcrowd~~ (Arne)

**Comment by Realtin** [comment] 2016-04-18 19:03
- I'll contact my Friend at [Futurice](http://futurice.com/) who already promised me to approve of the sponsoring (for anything less than 350€)

**Comment by plexus** [comment] 2016-05-05 11:43
This page is now up to date, so you can point sponsors there. http://clojurebridge-berlin.github.io/sponsor-us/

**Comment by vsmart** [comment] 2016-05-08 18:08
Got in touch with 
- metosin 
- lambdawerk

**Comment by Realtin** [comment] 2016-05-09 00:11
Got in touch with Futurice

**Comment by plexus** [comment] 2016-05-09 16:06
Cognitect has confirmed they can pay for the notebooks (€500), making them the official Gold Sponsor :)

I've also contacted BitCrowd and SouncCloud, and followed up with Gitter.

**Comment by plexus** [comment] 2016-05-29 07:47
I think we can wrap this up. Not as wildly successful a funding drive as last time, but we also didn't put in as much effort as last time. Looking at the results it should all work out.
- Wunderlist provides location and drinks
- We'll use Cognitect's (500) and Soundcloud's Women in Engineering (400) contributions towards catering.
- We got an extra 500 going into Travis Foundation (Metosin+LambdaWerk), which can be used for breakfast, cupcakes, stickers, etc.

We didn't find a Platinum (600) sponsor, but we won't do notebooks or t-shirts so that's roughly the same amount saved.

**Comment by socksy** [comment] 2016-05-29 12:13
Apologies for lack of clear communication on this front: Nicola has arranged ClojureBridge Berlin branded notebooks to be sponsored directly by Babbel, as they were willing to order some from their supplier directly, with a budget of 1000€, so she ordered 260. The catch is, because it was arranged so late there was no chance for a test run, and they may not arrive in time (confirmed delivery date is 17th of June, so it's going to be tight at the very least). I don't know whether she's ordering to Babbel's address or Wunderlist, but I imagine to Babbel.

I have also approached Red Pineapple Media mid last week, and was given some hemming and hawing over the minimum price. I'll push again tomorrow, and if we don't have something more concrete by the meeting in the evening let's drop them.

**Comment by Realtin** [comment] 2016-05-29 12:17
Also futurice gave 250€.

**Comment by plexus** [comment] 2016-05-30 08:54
Wow that's very cool and generous of Babbel! Sorry I had forgotten about Futurice. Seems we're in a good place financially.

**Comment by Malwine** [comment] 2016-07-25 09:11
@plexus Can we close this?

**Closed as completed** 2016-08-01 10:23 UTC
